version: '3.8'

services:
  upload-service:
    image: upload-service:1.0
    ports:
      - "3000:3000"
    environment:
      - S3_ACCESS_KEY_ID=28cc04cc25ebf7a76e0000811f95e8b4
      - S3_SECRET_ACCESS_KEY=e91032aa213842333833351700bba1c30e490af87605dc97af78d7e889415929
      - S3_ENDPOINT=https://4d1ec783bad1c616696abe541ec3e06c.r2.cloudflarestorage.com
      - REDIS_HOST=redis
    depends_on:
      - redis

  deploy-service:
    image: deploy-service:1.0
    ports:
      - "8000:3000"  # Exposes port 3000 of the container as port 8000 on the host
    environment:
      - S3_ACCESS_KEY_ID=28cc04cc25ebf7a76e0000811f95e8b4
      - S3_SECRET_ACCESS_KEY=e91032aa213842333833351700bba1c30e490af87605dc97af78d7e889415929
      - S3_ENDPOINT=https://4d1ec783bad1c616696abe541ec3e06c.r2.cloudflarestorage.com
      - REDIS_HOST=redis
    depends_on:
      - redis
      - upload-service

  request-handler:
    image: request-handler:1.0
    ports:
      - "3001:3001"
    environment:
      - S3_ACCESS_KEY_ID=28cc04cc25ebf7a76e0000811f95e8b4
      - S3_SECRET_ACCESS_KEY=e91032aa213842333833351700bba1c30e490af87605dc97af78d7e889415929
      - S3_ENDPOINT=https://4d1ec783bad1c616696abe541ec3e06c.r2.cloudflarestorage.com
      - REDIS_HOST=redis
    depends_on:
      - upload-service
      - deploy-service

  frontend:
    image: frontend:1.0
    ports:
      - "5173:5173"
    depends_on:
      - request-handler

  redis:
    image: redis:latest
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis-data:
